// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/search-properties.ts
import { createClient } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
var search_properties_default = defineTool({
  name: "search_properties",
  title: "Search properties",
  description: "Search approved property listings on Immo Link S\xE9n\xE9gal. Filter by city, type, price range, bedrooms, and more.",
  inputSchema: {
    city: z.string().optional().describe("Filter by city (e.g. Dakar, Thi\xE8s, Saly)."),
    type: z.string().optional().describe("Property type (e.g. villa, appartement, maison, terrain, bureau)."),
    minPrice: z.number().optional().describe("Minimum price in FCFA."),
    maxPrice: z.number().optional().describe("Maximum price in FCFA."),
    minBedrooms: z.number().int().optional().describe("Minimum number of bedrooms."),
    status: z.string().optional().describe("Listing status (e.g. '\xE0 vendre', '\xE0 louer'). Defaults to all."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false } }
    );
    let q = supabase.from("properties").select(
      "id,title,type,city,location,price,bedrooms,bathrooms,surface,status,is_featured,is_premium,images,created_at"
    ).eq("approval_status", "approved").order("created_at", { ascending: false }).limit(input.limit ?? 20);
    if (input.city) q = q.ilike("city", `%${input.city}%`);
    if (input.type) q = q.ilike("type", `%${input.type}%`);
    if (input.status) q = q.ilike("status", `%${input.status}%`);
    if (input.minPrice != null) q = q.gte("price", input.minPrice);
    if (input.maxPrice != null) q = q.lte("price", input.maxPrice);
    if (input.minBedrooms != null) q = q.gte("bedrooms", input.minBedrooms);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { properties: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-property.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_property_default = defineTool2({
  name: "get_property",
  title: "Get property details",
  description: "Fetch full details of one property listing by its ID.",
  inputSchema: {
    id: z2.string().uuid().describe("Property UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false } }
    );
    const { data, error } = await supabase.from("properties").select("*").eq("id", id).eq("approval_status", "approved").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: "Property not found." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { property: data }
    };
  }
});

// src/lib/mcp/tools/list-articles.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_articles_default = defineTool3({
  name: "list_articles",
  title: "List published articles",
  description: "List published real-estate articles from the Immo Link blog.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Max results (default 10)."),
    featuredOnly: z3.boolean().optional().describe("Only featured articles.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, featuredOnly }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false } }
    );
    let q = supabase.from("articles").select("id,slug,title,excerpt,featured_image,is_featured,published_at,views").eq("status", "published").order("published_at", { ascending: false }).limit(limit ?? 10);
    if (featuredOnly) q = q.eq("is_featured", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { articles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-article.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^3.25.76";
var get_article_default = defineTool4({
  name: "get_article",
  title: "Get article",
  description: "Fetch a published article by its slug.",
  inputSchema: {
    slug: z4.string().min(1).describe("Article slug.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false } }
    );
    const { data, error } = await supabase.from("articles").select("*").eq("slug", slug).eq("status", "published").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: "Article not found." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { article: data }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "immo-link-senegal-mcp",
  title: "Immo Link S\xE9n\xE9gal MCP",
  version: "0.1.0",
  instructions: "Tools to search and read public real-estate listings and articles from Immo Link S\xE9n\xE9gal (immolinksenegal.com). Use `search_properties` to find listings, `get_property` for full details, `list_articles` and `get_article` for the blog.",
  tools: [search_properties_default, get_property_default, list_articles_default, get_article_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
